development:
  adapter: postgresql
  encoding: unicode
  database: budget-app
  pool: 5
  host: localhost
  username: postgres
  password: welcome@2022

test:
  adapter: postgresql
  encoding: unicode
  database: budget-app
  pool: 5
  username: postgres
  password: welcome@2022

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
